"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Fixity.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,  'iconfile':'logo_sign_trans.icns','resources':'bin,schedules,reports,history,debug'}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
